### ISSUE TITLE
Set up code quality badges

### ISSUE THREAD

**Issue by u20437863-James-Butler** [COS301-SE-2022/Conversation-Catcher#7]
Code quality badges
(a) Code Coverage | Coveralls, Codecov, SonarCloud
(b) Build | AppVeyor, GitHub Actions, CircleCI, Drone, Netlify, Sonar Tests (SonarCloud), Travis
(c) Requirements | requires.io
(d) Issue tracking | GitHub Issues
(e) Monitoring | NodePing, PingPong, Security Headers, Uptime Robot

**Comment by u20437863-James-Butler** [comment]
Only one left is monitoring, but since we haven't set up hosting yet we may not get it working for this demo. It shouldn't take long to set up, I just need a working URL to where our page is hosted.

**Comment by u20437863-James-Butler** [comment]
@RRduToit should I close this issue, or should I wait for hosting this sprint?

**Comment by RRduToit** [comment]
@u20437863-James-Butler  we can create a separate issue for setting up the hosting part

**Comment by u20437863-James-Butler** [comment]
Ok, will do
